apiVersion: v1
kind: Pod
metadata:
  name: db
  labels:
    app: voting-app
    env: development
    pod: db-pod
spec:
  containers:
    - name: postgres
      image: postgres
      ports:
        - containerPort: 5432
      env:
        - name: POSTGRES_USER
          value: "postgres"
        - name: POSTGRES_PASSWORD
          value: "postgres"