apiVersion: v1 
kind: Service
metadata:
  name: redis
  labels:
    app: voting-app
    env: development
spec:
  type: ClusterIP
  ports:
    - port: 6379
      targetPort: 6379
  selector:
    pod: redis
