apiVersion: v1 
kind: Service
metadata:
  name: result-app-service
  labels:
    app: voting-app
    env: development
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30081
  selector:
    pod: result-app-pod
  