apiVersion: v1 
kind: Service
metadata:
  name: voting-app-service
  labels:
    app: voting-app
    env: development
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080
  selector:
    pod: voting-app
  