apiVersion: v1
kind: Pod
metadata:
  name: worker
  labels:
    app: voting-app
    env: development
    pod: worker-pod
spec:
  containers:
    - name: worker
      image: kodekloud/examplevotingapp_worker:v1